version: 0.2
phases:
  install:
    commands:
      - echo install steps...
  pre_build:
    commands:
      - ls -la

      - echo Check AWS, Git
      - aws --version && git --version
      - echo Check ENV Variable
      - printenv

      - pwd

      - echo Logging into AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
      - REPOSITORY_URI=518667233221.dkr.ecr.ap-southeast-2.amazonaws.com/go-demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo build Docker image on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest -f deployment/dockerfiles/dockerfiles-go-demo .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing Image Definitions File...
      - printf '[{"name":"go-demo","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > go-demo.json
artifacts:
  files: go-demo.json